language: python

python:
  - "3.7"

script:
  - python adventofcode/runtests.py --onlycheap
  - python adventofcode/runtests.py --onlyexpensive
  - python adventofcode/profile.py
  - coverage run adventofcode/runtests.py --all && coverage xml && python-codacy-coverage -r coverage.xml
