language: python
python: "3.7"

# Those requirements are needed here because of not supporting 3.7 out of the box.
# https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905
sudo: required
dist: xenial

script:
  - cd adventofcode
  - echo -e "travis_fold:start:Cheap"; echo -e "\e[0KCHEAP TESTS" && python -m runtests --onlycheap && echo "travis_fold:end:Cheap"
  - echo -e "travis_fold:start:Expensive"; echo -e "\e[0KEXPENSIVE TESTS" && python -m runtests --onlyexpensive && echo "travis_fold:end:Expensive"
  - echo -e "travis_fold:start:Profile"; echo -e "\e[0KPROFILING" && python -m profile && echo "travis_fold:end:Profile"
  - echo -e "travis_fold:start:Coverage"; echo -e "\e[0KCOVERAGE" && ( coverage run runtests.py --all --sequential && coverage xml && python-codacy-coverage -r coverage.xml ) && echo "travis_fold:end:Coverage"
