language: python

python:
  - "3.6"

script:
  - python adventofcode/runtests.py -m "not time_expensive"
  - python adventofcode/runtests.py -m "time_expensive"
  - python adventofcode/profile.py
  - coverage run adventofcode/runtests.py -m "" && coverage xml && python-codacy-coverage -r coverage.xml