language: python
python: "3.7"

# Those requirements are needed here because of not supporting 3.7 out of the box.
# https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905
sudo: required
dist: xenial

script:
  - echo -e "travis_fold:start:Cheap tests\nRunning cheap tests\n"; python -m adventofcode.runtests --onlycheap; echo "travis_fold:end:Cheap tests"
  - echo -e "travis_fold:start:Expensive tests\nRunning expensive tests\n"; python -m adventofcode.runtests --onlyexpensive; echo "travis_fold:end:Expensive tests"
  - echo -e "travis_fold:start:Profile\nRunning profiling\n"; python -m adventofcode.profile; echo "travis_fold:end:Profile"
  - echo -e "travis_fold:start:Coverage\nRunning coverage\n"; ( coverage run adventofcode/runtests.py --all && coverage xml && python-codacy-coverage -r coverage.xml ); echo "travis_fold:end:Coverage"
