language: python
python: "3.7"

# Those requirements are needed here because of not supporting 3.7 out of the box.
# https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905
sudo: required
dist: xenial

script:
  - python adventofcode/runtests.py --onlycheap
  - python adventofcode/runtests.py --onlyexpensive
  - python adventofcode/profile.py
  - coverage run adventofcode/runtests.py --all && coverage xml && python-codacy-coverage -r coverage.xml
